### ISSUE TITLE
 Android 13+ per-app language support

### ISSUE THREAD

**Issue by Korb** [vbresan/HealthyBatteryCharging#2]
I would prefer to take advantage of the ability provided in the latest versions of the OS to change the languages of installed applications from a single interface.

Read more about it in the article "[Change app language on your Android phone](https://support.google.com/android/answer/12395118)" of the official OS help.

[Screenshot](https://drive.google.com/file/d/1rhT3cFpo8cpeLrXIPteFH-0202ks_IYy/view)

**Comment by vbresan** [comment]
The app currently supports English language only. Which language would you prefer to have instead?

**Comment by Korb** [comment]
Ukrainian, of course. 👋

**Comment by vbresan** [comment]
Though my profile photo might suggest otherwise, I am not Ukrainian and do not speak Ukrainian. Would you kindly provide the translations?

**Comment by Korb** [comment]
I've never done technical translations on Github. Please tell me which file I need to take to translate the interface labels? Also, I know Russian and can translate the application into it.

Is Google's new approach compatible with the method you're using to switch app locales?

**Comment by vbresan** [comment]
Thank you for your help!

Before we proceed, I will update the English text resources and set up a translation platform. Once this is done, I will let you know. The first additional language, Ukrainian, will not be added directly via GitHub, as GitHub is not very translator-friendly. After the app with the Ukrainian language is published and everything runs smoothly, we can discuss adding Russian as a direct contribution via GitHub.

**Comment by vbresan** [comment]
@Korb I have set up the project on Weblate. You can log in with your GitHub account, if you prefer it that way. Weblate is new to me too, so I am still learning. 

You can start translating app string resources [here](https://hosted.weblate.org/projects/healthy-battery-charging/app/uk/) and metadata (app description, etc.) [here](https://hosted.weblate.org/projects/healthy-battery-charging/metadata/uk/).

Translations of previous changelog files are not necessary. If you have any issues, let me know and we'll try to figure them out.

Thanks in advance!

**Comment by Korb** [comment]
> You can start translating app string resources [here](https://hosted.weblate.org/projects/healthy-battery-charging/app/uk/) and metadata (app description, etc.) [here](https://hosted.weblate.org/projects/healthy-battery-charging/metadata/uk/).

Done.

**Comment by vbresan** [comment]
Big thanks once again for your contribution! Your translations have been added and this request is implemented in release 2.0.3.

Unfortunately, since your GitHub and Weblate accounts are not connected, you are still not shown in the **Contributors** sidebar. However, I have added you to the app's **README**.

**Comment by vbresan** [comment]
@Korb Perhaps you could connect the accounts and translate the latest changelog? Once the change is merged, you should appear as contributor.

**Comment by Korb** [comment]
> translate the latest changelog?

Done.
